### ISSUE TITLE
RDS scanning

### ISSUE THREAD

**Issue by jennyb** [tomjon/piSpecMon#79]
The RDS scanning was designed as such:
go to channel. Measure signal level. if signal level > x then wait for y seconds. if name text decoded then wait for z seconds for program text. 
What it actually does:
go to channel. wait for y (30)seconds. if signal > x then wait for z (300 )seconds 
I could be wrong with this, but this is what it appears to do. 
So, just get a couple of signal readings, compare to threshold and wait y seconds if that passes. Then z seconds if you get program name. Just adjusting the timings speeds the RDS scan up dramatically

**Comment by tomjon** [comment]
You need to sit on each frequency for a little while until a proper strength is reported (i.e. it is zero for a while). Here is the algorithm that is currently implemented in monkey.py:

For each frequency in turn:
* read strength for X seconds, or until a threshold L is achieved
* continue on to next frequency if threshold not achieved
* decode RDS Name for Y seconds, or until a name is decoded
* continue on to next frequency if no name is decoded
* decode RDS Text for Y seconds

I think what we need is an additional timeout, Z, so that the last step becomes
* decode RDS Text for Z seconds

Then you can set Z=0 if you don't care about RDS text.
